version: 2

registries:
  npm-registry-npm-pkg-github-com:
    type: 'npm-registry'
    url: 'https://npm.pkg.github.com'
    token: ${{secrets.GITHUB_TOKEN}}

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      time: '04:00'
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    reviewers:
      - 'rconjaerts'
    labels:
      - 'dependabot'
    registries:
      - 'npm-registry-npm-pkg-github-com'

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
      time: '04:00'
    reviewers:
      - 'rconjaerts'
    labels:
      - 'dependabot'

  - package-ecosystem: 'github-actions'
    directory: '.github/workflows'
    schedule:
      interval: 'weekly'
      time: '04:00'
    reviewers:
      - 'rconjaerts'
    labels:
      - 'dependabot'
