name: Build and Push to Container Registry

on:
  push:
    branches: [main]

# Environment variables available to all jobs and steps in this workflow
env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
  USE_GKE_GCLOUD_AUTH_PLUGIN: True
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REGISTRY_HOSTNAME: europe-docker.pkg.dev
  REGISTRY_REPONAME: docker-eu

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GKE_KEY }}'

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          install_components: 'gke-gcloud-auth-plugin'

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          # Set up docker to authenticate
          # via gcloud command-line tool.
          gcloud auth configure-docker europe-docker.pkg.dev

      # Get the repo name
      - run: echo "REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//")" >> $GITHUB_ENV
        shell: bash

      # Build the Docker image
      - name: Build
        run: |
          docker build -t "$REGISTRY_HOSTNAME"/"$GKE_PROJECT"/"$REGISTRY_REPONAME"/"$REPOSITORY_NAME":"$GITHUB_SHA" \
            --build-arg GITHUB_TOKEN="$GITHUB_TOKEN" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" .

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |
          docker tag $REGISTRY_HOSTNAME/$GKE_PROJECT/$REGISTRY_REPONAME/$REPOSITORY_NAME:$GITHUB_SHA $REGISTRY_HOSTNAME/$GKE_PROJECT/$REGISTRY_REPONAME/$REPOSITORY_NAME:latest
          docker push $REGISTRY_HOSTNAME/$GKE_PROJECT/$REGISTRY_REPONAME/$REPOSITORY_NAME:$GITHUB_SHA
          docker push $REGISTRY_HOSTNAME/$GKE_PROJECT/$REGISTRY_REPONAME/$REPOSITORY_NAME:latest
